### ISSUE TITLE
Wire Diagram

### ISSUE THREAD

**Issue by IGLO70** [moeskerv/esp32-weather-station#1]
Do you have a wire diagramm for this projekt?

**Comment by moeskerv** [comment]
Hi IGLO70,

actually I don't have a wiring diagram, but if you use the parts I did it is quite easy to build the hardware. The ESP32 module and the display can be directly connected as the display has a connector for the ESP32 feather module. The two sensors are I2C devices, so just connect GND, VCC (3V), SDA and SCL from to sensors to the ESP32 feather board. Check the linked datasheets for the details.

Let me know if any questions left!
