### ISSUE TITLE
s16 results not declared

### ISSUE THREAD

**Issue by joelpfeiffer** [moeskerv/esp32-weather-station#2]
hi,

I really like your project. I only have 1 problem.
when uploading to the huzzah esp32 I get a error saying s16 not declared in this scope.

```
 // get readngs from SDS30 sensor
    s16 result = 0;

```

do you know how I can solve this?

regards,

**Comment by moeskerv** [comment]
Hi,

thanks for the feedback! Seems that s16 and u16 data type definitions got lost in the libraries I use. I changed the data types so that it should work now.

Still I see a warning in the sps30 library, didn't test if the build works. Currently I have my hardware not available.

Have fun!

**Comment by joelpfeiffer** [comment]
awesome, I'm gonna try to figure out how to work the sps30 (first time using it)
anyway thank you for your fast response

**Comment by moeskerv** [comment]
I meanhwhile tested the build and it works, warning in sps30 library can be ignored
