### ISSUE TITLE
Sps30 libary.

### ISSUE THREAD

**Issue by joelpfeiffer** [moeskerv/esp32-weather-station#3]
Hi, great to here it’s still working.
Do you know what version of the sps30 library you are using.

I cannot get to work using the latest version of the sps30 libary.

Regards,

**Comment by moeskerv** [comment]
Hi, I'm using the version 0.9.0 of the sps30 library which throws some warnings during compilation, but it works.

Can you give some details about what exactly goes wrong?

**Comment by moeskerv** [comment]
I made a PR to fix the compiler warnings in the sps30 library, lets see if it gets merged.
https://github.com/Sensirion/arduino-sps/pull/21
